---
deployment:
  tasks:
    - export DEPLOYPATH=/home/shargtvh/gemonagroup/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp styles.css $DEPLOYPATH
    - /bin/cp script.js $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
